### ISSUE TITLE
dialogues ID will be created next to the last dialogues ID from previous object

### ISSUE THREAD

**Issue by jokerrider007** [Arnavion/libjass#115]
when I use libjass.ASS.fromUrl multiple time.  ASS object dialogues ID will be created next to the last dialogues ID from previous ASS object.

![capture1](https://user-images.githubusercontent.com/12674933/52350372-05404780-2a5b-11e9-960d-72c9e134a3ba.PNG)

![capture2](https://user-images.githubusercontent.com/12674933/52350465-3caef400-2a5b-11e9-9c37-eff81bd58154.PNG)

How can I get ASS object dialogues ID doesn't relate form previous object?

**Comment by Arnavion** [comment]
It doesn't matter. The ID doesn't need to start from 0; it only needs to be unique.

**Comment by jokerrider007** [comment]
Can I clear object ID start to 0?
l need to each object dialogue start by 0 before storing to the database.

**Comment by Arnavion** [comment]
If you're sure that you're going to only create and work with one `ASS` object at a time (ie you're not going to create `Dialogue` objects for multiple `ASS` at the same time), then you can set `Dialogue._lastDialogueId` to `-1` before creating the next `ASS` object. Every newly created `Dialogue` object sets its id to [`++Dialogue._lastDialogueId`](https://github.com/Arnavion/libjass/blob/ee97d1d0f31d6520bd558b37e298f2c2b88147a9/src/types/dialogue.ts#L75)

Alternatively use the `Dialogue`'s index in the `ass.dialogues` array as your database key instead of its `id` property.
