### ISSUE TITLE
Safari: TypeError: Map constructor does not accept arguments

### ISSUE THREAD

**Issue by pennello** [Arnavion/libjass#34]
Looks like there is a JavaScript error preventing the library from loading up on Safari.  I was able to reproduce by just loading [the demo page](http://arnavion.github.io/libjass/demo/index.xhtml).
![screen shot 2015-02-13 at 12 00 13 pm](https://cloud.githubusercontent.com/assets/5225759/6194297/fe92a878-b377-11e4-9ef6-c99ed929f60e.png)
I'm running Safari Version 8.0.3 (10600.3.18) on OS X Yosemite 10.10.2 (14C109).

Let me know what other information you might need to take a look.

**Comment by Arnavion** [comment]
Ah, interesting. That is from the code that detects if the global Map constructor supports the `iterable` parameter. On other browsers that don't support it, the argument is ignored, but it seems JSC explicitly throws an error for it.

The fix is simple, just catch the error and treat is the same way.

**Comment by pennello** [comment]
Awesome; thanks!
