### ISSUE TITLE
Timing out of sync after network lag or heavy animation

### ISSUE THREAD

**Issue by Dador** [Arnavion/libjass#42]
Happens often when playing video with heavy animation (heavy for libjass, fine in native player). Also that happens on regural subtitles on mobile devices (such as Chrome on Android tablet). In case of network lag (html5 player waiting for video to load) that happens too.

These delays started after implementing new AutoClock. AutoClock take value of currentTime from html5 video only once. So difference between time in AutoClock and currentTime in html5 video growing and growing. Re-sync of timing happens only if seek to other part of video. It doesn't happens on play & pause.

Maybe sync time each "onupdatetime" event? (but there may be noticeable gaps, not sure)
BTW, why you decided to switch from "onupdatetime" to manual clock only?

**Comment by Arnavion** [comment]
>AutoClock take value of currentTime from html5 video only once.

It should be taking the currentTime value once every rAF tick. As soon as the currentTime changes (about 1 every 250ms except on IE where it's more frequent) it will snap to that new time. The purpose of AutoClock is to interpolate the timestamps in between changes of video.currentTime (or other external drivers, like say setTimeout) for less bleeding.

Are you sure it only takes it on play and seek? Does it happen on desktop as well or only mobile? I cannot repro it on desktop.

>Maybe sync time each "onupdatetime" event?

That is basically what it already does. As you can see, AutoClock's constructor takes a driver in the form of a function () -> currentTime. For VideoClock, this is the function () => videoElement.currentTime. In other words it doesn't use the ontimeupdate event itself, but the currentTime updates with the same frequency so it amounts to the same thing.

>BTW, why you decided to switch from "onupdatetime" to manual clock only?

Even before AutoClock, VideoClock did not use the timeUpdate event. As I said it is very infrequent and so there's too much bleeding. Also browsers are inconsistent on whether they fire timeUpdate events during seeking, or while holding the seek thumb down and not moving it, etc. So back then VideoClock itself polled video.currentTime in every rAF callback.

However if you wanted to use, say, a flash player instead of video element, then you could not use VideoClock. So this interpolation behavior of VideoClock would not be available to you and you would have to code it yourself. So AutoClock was introduced to extract this behavior from VideoClock in a way that is independent of the video element. That's why it takes the driver function - this is an abstraction over any form of playback.

**Comment by Dador** [comment]
That's how it looks from side:
- Start play video
- Opening with various heavy effects (which lags around 2 seconds)
- All dialogues after opening is delayed for 2 seconds.

After testing it many times I think Chrome Mobile reports wrong currentTime after such lags. For example at real video position 01:00 it reports 00:58.
Only after seek it starts to report right currentTime. That's why I thought "it only takes it on play and seek".

Maybe that somehow connected with mechanism of hardware acceleration in Android. I'll try to test that case in other mobile browsers and also will try to create reduced test.

But most likely the problem is not in libjass.

**Comment by Arnavion** [comment]
That is interesting. Thanks for testing. I don't have any mobile to test on, so I appreciate it.

**Comment by Dador** [comment]
Works fine in stock Android browser. So bug only in Chrome Mobile.

I created issue and reduced test in Chromium project. Please star it - https://code.google.com/p/chromium/issues/detail?id=509010

I close this issue cause problem not in libjass.
