### ISSUE TITLE
Manual clock behavior weird

### ISSUE THREAD

**Issue by bsuh** [Arnavion/libjass#44]
Calling `this.disable()` first sets `this._enabled` to false, then calls `this.pause()` which does nothing because `this._enabled` is false, then calls `this.stop()`, which works as expected and makes `WebRenderer` hide the subtitle container by dispatching `ClockEvent.Stop`.

Then calling `this.enable()`, sets `this._enabled` but subsequent `this.tick()` calls call `this.play()` which doesn't send the `ClockEvent.Play` event, because it isn't `this._paused` is false (the `this.pause()` call during `this.disable()` did nothing). Since no `ClockEvent.Play` is received `WebRenderer` doesn't restore the visibility of the subtitle container.

What I would expect to work:
```
webRenderer.disable();
webRenderer.enable();
```

What's actually needed:
```
webRenderer.disable();
webRenderer.enable();
manualClock.pause();
manualClock.play();
```

**Comment by Arnavion** [comment]
manualClock.pause() is not supposed to be required. That is a bug, which can be fixed by setting this._enabled to false *after* calling this.pause(). I'm doing this, as well as adding some long-awaited tests for clock behavior.

Note that enabling a clock is supposd to leave it in a paused state until it is ticked to a new currentTime. As such, you don't have to call manualClock.play(); it will be implicitly called for you when you call manualClock.tick() with some time that is different from the clock's current time.
