### ISSUE TITLE
Font scale (\fscx, \fscy) is wrong (bigger than should be)

### ISSUE THREAD

**Issue by Dador** [Arnavion/libjass#47]
Seems like proportion is right but whole text becomes much bigger than should be.

In libjass:
![libjass-1](https://cloud.githubusercontent.com/assets/974924/9022954/ca9bd144-3891-11e5-8a94-9e21fcd141ea.png)

In Aegisub (libass):
![libass](https://cloud.githubusercontent.com/assets/974924/9022976/329db88e-3892-11e5-9822-af9795c09c54.png)

Test script:
```
[Script Info]
Title: 
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1280
PlayResY: 720
Scroll Position: 0
Active Line: 0
Video Zoom Percent: 1
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Trebuchet MS,54,&H00FFFFFF,&H000000FF,&H00020713,&H00000000,-1,0,0,0,100,100,0,0,1,2.55,0,2,0,0,42,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:10:00.00,Default,,0,0,0,,{\fscx50}xxxxxxxxxxxxxxxxx
Dialogue: 0,0:00:00.50,0:10:00.00,Default,,0,0,0,,{\fscy50}yyyyyyyyyyyyyyyyy
```

**Comment by Arnavion** [comment]
For (1), it renders x as "font-size: 46px, scaleY(2)" instead of "font-size: 23px, scaleY(2)". Similarly it renders y as "font-size: 23px, scaleY(0.5)" instead of "font-size: 46px, scaleY(2)"

`const fontSize = (this._scaleY * this._fontSizeForLineHeight(this._fontName, this._fontSize * (isTextOnlySpan ? this._fontScaleY : 1), this._fontSizeElement)).toFixed(3);`

should be

`const fontSize = (this._scaleY * this._fontSizeForLineHeight(this._fontName, this._fontSize * (isTextOnlySpan ? this._fontScaleX : 1), this._fontSizeElement)).toFixed(3);`

**Comment by Arnavion** [comment]
@Dador Can you move (2) into its own issue?

**Comment by Dador** [comment]
Yeah, done: #54
I close current issue cause you already fixed it.
