### ISSUE TITLE
Margin problem on mobile device

### ISSUE THREAD

**Issue by giggioman00** [Arnavion/libjass#64]
In PC desktop everything works great, but there is a very critical problem on mobile device.
Margin bottom seems to be 0 on mobile device. Then, when there is a subtitle line with 2 line, subtitles are overlying each other... 

So there is just 1 line but is impossible to read since there are 2. Please take a look at the screen, this show there is no margin and the overlay of 2 line sub:

http://s8.postimg.org/7wp24f5zo/Screenshot_2016_01_24_22_12_15.jpg

**Comment by giggioman00** [comment]
I don't know much but I think the issue is the same as before, but this time happen when the ratio and the video are resized.

**Comment by giggioman00** [comment]
If you don't have the time for fix the margin on mobile device it doesn't matter but please, could you at least fix the overlap of the subs? making them at least readable...

**Comment by Arnavion** [comment]
It is of no use to me if you report a bug report without any of the following information:

- URL of the website where you see the issue
- URL of video, or atleast the original dimensions of the video
- URL of ASS file, or atleast just the part where you're seeing the issue
- Whether you're using libjass.js or videojs-ass or something else

If you don't give me any of that then I have no way to help you.

If you don't want to share anything, then go try it on http://arnavion.github.io/libjass/demo/index.xhtml?disableSvg and see if it still happens. If it does, then follow the instructions at the bottom for what information a useful bug needs to contain. Otherwise there's nothing I can do.

**Comment by giggioman00** [comment]
Info are the same of the last time...

Video: http://test995.altervista.org/index.php/player/8/8
ASS: http://test995.altervista.org/components/com_contushdvideoshare/videos/8_ITA1613213799.ass

videojs-ass with libjass

**Comment by Arnavion** [comment]
If you're seeing the same problem with http://arnavion.github.io/libjass/demo/index.xhtml?disableSvg then give me a screenshot of it.

**Comment by giggioman00** [comment]
Ok, here you can find the screeshot: 
![tmp_8474_screenshot_2016_01_29_14_10_18106422537](https://cloud.githubusercontent.com/assets/11320345/12676456/b8aa7f28-c692-11e5-9886-053d925c2c48.jpg)

The line of the screenshot is this: 
Dialogue: 0,0:00:00.00,0:01:15.00,Default,,0000,0000,0000,,{\an8}This is a sample ASS file\Nthat showcases some of libjass's capabilities.

Because is the only dialogue of the script that have 2 lines. If it was at \an2 wouldn't change anything though

**Comment by Arnavion** [comment]
Your browser is ignoring `<br>` *and* has some other style that's causing multiple `<span>` to overlap. Either your browser has some broken default styles or you have some custom user-styles. Try another browser.

**Comment by giggioman00** [comment]
I have a friend that also use firefox with Android. Asking him to check, he said that everything works great. So yeah, it was my problem. Thank you.
Also, changing to chrome everything works fine even for me.

Anyway I can't understand why. I didn't changed anything on my mobile firefox, I just downloaded and installed.

**Comment by Arnavion** [comment]
Cool. If you ever find out what it was then please post it here in case someone else hits it.
