### ISSUE TITLE
realtime dialogues changes/editing

### ISSUE THREAD

**Issue by elBarkey** [Arnavion/libjass#68]
Hi first of all thanks for this great libs.
Is there any implementation to achieve dialogues,styles,start time changes on realtime?
Thanks.

**Comment by Arnavion** [comment]
It's not documented because it's not explicitly supported (yet), but yes you can do it.

Modify the private properties of the Dialogue object (eg `ass.dialogues[0]._start = 100;`). Then call [`renderer.resize(width, height, left, top)`](http://arnavion.github.io/libjass/api.xhtml#libjass.renderers.WebRenderer.resize) with the same values for those parameters as what it already has. Resizing to the same size will clear the internal cache of pre-rendered subtitles, so they'll be regenerated according to the changes you've made.

**Comment by elBarkey** [comment]
thanks @Arnavion 
I got it, what about the defined styles changes?
it's a bit confusing to me about how i can set the "Maped" child object of each styles object.

**Comment by Arnavion** [comment]
[ASS.styles](http://arnavion.github.io/libjass/api.xhtml#libjass.ASS.styles) is an [ES6 Map.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) You would use `ass.styles.get("Default")` and so on.

**Comment by elBarkey** [comment]
I know it. The problem is when i tried the following  snippet.
```javascript
var defStyle = ass.styles.get("Default");
defStyle.underline = true;
ass.styles.set("Default",defStyle);
```
then as you suggest above, i call the renderer.resize function.
but nothing changes at all!, then i realize that
```javascript
console.log(ass.styles.get("Default").underline)
```
still returning false. please point me to the right direction.

the same method i tried on dialogues array works fine, since its easy to mofidy regular array.

**Comment by Arnavion** [comment]
As I said, you have to modify the private properties, so `defStyle._underline = true;` `underline` is just a getter, so trying to set it is a no-op.

**Comment by elBarkey** [comment]
that's it, thanks @Arnavion 
i didn't know it was that simple :cry: 
thanks again for pointing me out.

**Comment by Statfine** [comment]
@Arnavion   how can i realtime changes/edit subtitle;  any method can parses _rawPartsString to _parts

**Comment by Arnavion** [comment]
What exactly do you want to do? You want to change the raw string of a Dialogue?

**Comment by Statfine** [comment]
@Arnavion   when i change first text 
*{\an8}{\fs12}This is a sample ASS file\Nthat showcases some of libjass's capabilities.* to  
*{\an8}{\fs12}This is a sample ASS file\N444*
i should first change _rawPartsString then according to the law change _parts
ass._dialogues[0]._rawPartsString = "{\an8}{\fs12}This is a sample ASS file\N44444.";
ass._dialogues[0]._parts[3]._value = '44444';
renderer.resize();

and this just a simple change. If a complex operation i should know the rule to change _rawPartsString to _parts;    if has any method parses _rawPartsString to _parts

**Comment by Arnavion** [comment]
You don't need to do that. You have easier options depending on what you start with. Either

- If you want to change a part and not the original string - Create a new `Dialogue` object, remove the old one from `ass.dialogues` array and append the new one. You don't even need to call `renderer.resize()` since every new `Dialogue` has a unique ID.

or

- If you want to change a part and not the original string - Change only the `_parts` array of the `Dialogue` and call `renderer.resize()` to refresh the cache. The `_rawPartsString` will be inconsistent but nothing uses it if `_parts` is set to non-null.

or

- If you want to change the original string and let it parse it into parts - Change `_rawPartsString` to whatever you want, then set `_parts` to `null` and call `renderer.resize()`. `_parts` will automatically be recreated from the new `_rawPartsString`.

**Comment by Arnavion** [comment]
Note that the first option is the only supported option since the others use private API.

**Comment by Statfine** [comment]
@Arnavion     first  thanks very much;  i think the first option is the conventional method; but how can i create a new Dialogue object , i used new libjass.Dialogue(template, ass) but no return

**Comment by Arnavion** [comment]
(Oh, I remembered wrong - there's no way yet to construct a `Dialogue` from parts. You can only construct it from the template.)

Anyway if you have the template then `new Dialogue(ass, template)` will give you a `Dialogue` object. Then you have to add it to the script object with `ass.dialogues.push(newDialogue);`, or replace an existing one with `ass.dialogues.splice(5, 1, newDialogue);`, etc

**Comment by Statfine** [comment]
￼
![wechatimg250](https://cloud.githubusercontent.com/assets/4608910/21450233/dd76990e-c92f-11e6-8848-383a99f67e37.jpeg)
sorry  what's wrong with me￼

**Comment by Arnavion** [comment]
You forgot the `new`

**Comment by Statfine** [comment]
@Arnavion  Thanks for your help. all is well 。
