### ISSUE TITLE
reverse construction of libjass.ASS object

### ISSUE THREAD

**Issue by elBarkey** [Arnavion/libjass#69]
Hi @Arnavion 
I've successfully manage some parsed libjass.ASS object properties to become editable. dialogues, timing, styles etc.
now i want to post the edited ASS object back to serverside.
is there any simple method i can use for this purpose ?

thanks

**Comment by Arnavion** [comment]
libjass does have some code to serialize and deserialize Part objects between webworkers. The relevant functions are [serialize and deserialize.](https://github.com/Arnavion/libjass/blob/18b5d88/src/webworker/misc.ts#L60-L92) But a) these functions are not public, and b) the mechanism they use (set private properties and use Object.create to rehydrate getters) only works for types like parts with simple properties (primitives, arrays), not complex ones like ASS. So that doesn't help you.

I've also had it in mind to implement exporting the ASS object back to a string (i.e. the opposite of ASS.parse), but it doesn't exist yet.

So no, there's no existing function. You'll have to implement your own serialization and deserialization mechanism.

**Comment by elBarkey** [comment]
I see, i'm working on it.
thanks for clear the things out.

**Comment by Arnavion** [comment]
With https://github.com/Arnavion/libjass/compare/d5831e6...a67ec29 I've implemented [libjass.serialize](https://arnavion.github.io/libjass/api.xhtml#libjass.serialize) and [libjass.deserialize](https://arnavion.github.io/libjass/api.xhtml#libjass.deserialize) that expose the API I linked above, and also extended to work with ASS objects. So `var str = libjass.serialize(ass);` will give you a string that you can later deserialize with `var ass = libjass.deserialize(str);`

If you want to build master with those commits yourself and use that, you can do that. Or wait for 0.12.0 release.
