### ISSUE TITLE
Wrong order in styles and wrong view of tiny border

### ISSUE THREAD

**Issue by XCanG** [Arnavion/libjass#70]
![image](https://cloud.githubusercontent.com/assets/1096010/13622963/e9a13688-e557-11e5-9142-061ff5e31e28.png)

At this moment shadow drop only text shadow, but need to drop text and border shadow, also a tiny cut first symbol at left (used font: BrushType).
Style:

```
Style: Announce,BrushType,70,&H00FFFFFF,&H000019FF,&H00225681,&H00000000,-1,0,0,0,100,100,0,0,1,3,3,2,15,15,21,1
```

Dialogue:

```
Dialogue: 0,0:03:39.07,0:03:41.29,Announce,,0,0,0,,в Птичью Клетку вместе со всеми жителями острова.
```

![image](https://cloud.githubusercontent.com/assets/1096010/13622968/f1a8402e-e557-11e5-85c8-d33d2ff4fdc0.png)

At this moment in subtitle used a tiny border and it work property in Aegisub and MPC-HC, also syle is

```
Style: SongJap,Arial,50,&H00FFFFFF,&H000019FF,&H00FA8000,&H00000000,0,-1,0,0,100,100,0,0,1,0.75,0,2,15,15,15,1
```

So, in browser I don't see it, I try to use 2, rather than 0.75 and see smal result, but not the same as in Aegisub and MPC-HC (also script resolution is 1920x1080)

```
Style: SongJap,Arial,50,&H00FFFFFF,&H000019FF,&H00FA8000,&H00000000,0,-1,0,0,100,100,0,0,1,2,0,2,15,15,15,1
```

(in browser)

Also know issue with wrong order ([already sended](https://github.com/Arnavion/libjass/issues/49)).

**Comment by Arnavion** [comment]
For the second one with the small border, the issue is that the dilation SVG filter uses integer radii (on Chrome anyway) instead of decimals, so a 0.75 radius is treated as 0. So the border you see is actually the text with no border. That's why it's so thin. I *could* round  0.75 up to 1 in this case, which is still not accurate but does look better...

That's for the SVG renderer. The text shadow renderer does a better job. It currently adds only integer outlines but after I fixed that it looks like Aegisub.

**Comment by XCanG** [comment]
Oh, what the reason. So, yea, if border something like 0.05 or 0.5 or 0.99 it need to be lifted to 1. May be if border 1.4 it need to be downed to 1, if 1.5, 1.6... lift to 2.
Just only exception for non-border variant.

Hope first and third problems can be solved.

**Comment by Arnavion** [comment]
I actually found a better way that keeps it accurate. feOffset filter does work with fractional values, so I can use it for the four corners of the outline.

**Comment by Arnavion** [comment]
That last commit should fix the first problem.
